version: '3.8'

networks:
 monitoring:
  driver: bridge

services:
 api-prediction:
  build: ./backend_rating
  image: shinbi/prediction_api:latest
  container_name: api-prediction
  ports:
   - 5000:5000
  restart: unless-stopped
  networks:
   - monitoring
